baseURL = 'https://example.org/'
languageCode = "zh-han"
title = "Hugo Theme y3say Dev"

theme = "y3say"

[params]

[params.homepage]
  slogan = "( 鱼如果有完整的记忆 )"
  
[menus]
  [[menus.main]]
    id = "home"
    name = "主页"
    pageRef = '/'
    weight = 1


[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'